
import localFont from "next/font/local";
import { AuthProvider } from "../../firebase/auth";
import "./globals.css";
import Nav from "./components/Nav";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "clio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
         <Nav />
        <main>{children}</main>
        
        </AuthProvider> 
      </body>
    </html>
  );
}
