
import localFont from "next/font/local";
import { AuthProvider } from "../../firebase/auth";
import "./globals.css";
import Nav from "./components/SideBar";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["400", "600", "700", "800"],variable: "--font-montserrat", });

export const metadata = {
  title: "clio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${montserrat.variable} antialiased`}>
        <AuthProvider>
        <main>{children}</main>
        </AuthProvider> 
      </body>
    </html>
  );
}
